coffee:
	@echo "Compiling coffeee"
	@coffee -c js/*.coffee
	@coffee -c js/*/*.coffee
	@echo "All done"

clean:
	@echo "Deleting compiled JS files"
	@rm js/bootstrap.js
	@rm js/models/*.js
	@rm js/views/*.js
	@rm js/routers/*.js
	@rm js/templates/*.js
	@rm js/collections/*.js
	@echo "All done"
